block/042: Log the executed command
Make it easier to analyze test failures by logging the executed command
in $FULL before executing it. Reduce code repetition by changing the
working directory to ${TEST_DEV_SYSFS}/queue before reading sysfs
attributes.

Link: https://github.com/linux-blktests/blktests/pull/261
Signed-off-by: Bart Van Assche <bvanassche@acm.org>
Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>

diff --git a/tests/block/042 b/tests/block/042
--- a/tests/block/042
+++ b/tests/block/042
@@ -19,17 +19,23 @@ device_requires() {
 test_device() {
 	echo "Running ${TEST_NAME}"
 
-	sys_max_segments=$(cat "${TEST_DEV_SYSFS}/queue/max_segments")
-	sys_dma_alignment=$(cat "${TEST_DEV_SYSFS}/queue/dma_alignment")
-	sys_virt_boundary_mask=$(cat "${TEST_DEV_SYSFS}/queue/virt_boundary_mask")
-	sys_logical_block_size=$(cat "${TEST_DEV_SYSFS}/queue/logical_block_size")
-	sys_max_sectors_kb=$(cat "${TEST_DEV_SYSFS}/queue/max_sectors_kb")
-
-	if ! src/dio-offsets "${TEST_DEV}" "$sys_max_segments" \
-	     "$sys_max_sectors_kb" "$sys_dma_alignment" \
-	     "$sys_virt_boundary_mask" "$sys_logical_block_size"; then
-		echo "src/dio-offsets failed"
-	fi
+	(
+		orig_dir=$PWD
+		cd "${TEST_DEV_SYSFS}/queue" || exit 1
+		cmd=(
+			"$orig_dir/src/dio-offsets"
+			"${TEST_DEV}"
+			"$(cat max_segments)"
+			"$(cat max_sectors_kb)"
+			"$(cat dma_alignment)"
+			"$(cat virt_boundary_mask)"
+			"$(cat logical_block_size)"
+		)
+		echo "${cmd[@]}" >>"$FULL"
+		if ! "${cmd[@]}"; then
+			echo "src/dio-offsets failed"
+		fi
+	)
 
 	echo "Test complete"
 }
